### PR TITLE
Add "oraclejdk8" in Travis CI configuration file

### PR DESCRIPTION
**Pull request by vbauer**

### CODE REVIEW

**Comment by lanwen** [comment]
think all other can be removed

**Comment by vbauer** [comment]
At the current moment `source` & `target` versions equal `1.7` (pom.xml), so maybe it will be better to keep it for now? It allows to check correctness of build for 1.7, otherwise it will be better to add [animal-sniffer-maven-plugin](http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/) What do you think?

**Comment by lanwen** [comment]
1.8 builds successfully 1.7 as target. BTW think it better to keep only oracle jdk 7 and 8. Or it will be too long builds on any pr

**Comment by vbauer** [comment]
> 1.8 builds successfully 1.7 as target.
Yes, ofc. I mean that Java 8 & Java 7 have different classes in runtime libraries, so if we'd like to remove Java 7 from travis configuration it will be better to use Animal Sniffer to check that we still using only Java 7 compatible classes (during compilation under Java 8).

> BTW think it better to keep only oracle jdk 7 and 8.
+1, I'll update PR asap.

**Comment by vbauer** [comment]
PR was updated.

**Pull request merged**
